import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nextjs14 application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} custom-container bg-customDark text-customWhite`}>
        <Navbar />
        <section className='min-h-[calc(100vh-9rem)] py-4'>
          {children}
        </section>
        <Footer />
      </body>
    </html>
  )
}
